{{- if .Values.kamaji.enabled }}
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: allow-konnectivity
  namespace: {{ . }}
spec:
  endpointSelector:
    matchLabels:
      k8s-app: konnectivity-agent
  egress:
    # Allow traffic to any Pod within the kube-system namespace
    # (Covers Metrics Server, CoreDNS, etc.)
    - toEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": kube-system

    # Allow traffic to Kyverno Admission Controller in its own namespace
    - toEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": kyverno
            app.kubernetes.io/instance: kyverno # Standard Kyverno label
      toPorts:
        - ports:
            - port: "9443"
              protocol: TCP

    # Allow traffic to the Nodes (Kubelet 10250)
    - toEntities:
        - host
        - remote-node
      toPorts:
        - ports:
            - port: "10250"
              protocol: TCP

    # Allow traffic to the API Server (Management Tunnel)
    - toEntities:
        - kube-apiserver
---
{{- end }}
